version: "3"
services:
    name-from-id:
        image: container-name-from-id:latest
        build:
            context: .
        container_name: name-web
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
        ports:
            - "8080:8080"